### PR TITLE
INET 4 compatible version of simulte - request to pull in new separate porting branch

### PR DESCRIPTION
**Pull request by wischhof**
In order to be able to use INET 4, significant changes had to be made to the simulte sources, including but not limited to:

- adaptation of UE, eNB, SGW, PGW to new node structure
- adapt all parts on network layer and above to use inet::Packet instead of cPacket
- using MessageDispatchers between the individual layers (->ProtocolTags, InterfaceReqs)
- update all ini files to use the new parameter names
- module initialization
- adaptations to new socket and application interfaces
- use new INET 4 class names 

In total, almost all source code files had to be touched - therfore, this is a quite large pull request. All simulations within the simulation folder (including the cars scenario which makes use of veins) are runnable. However, an in depth-comparison of the simulation results with those obtained with the INET 3 based version has not yet been done.

In order to enable a more in-depth testing by the community, this is a request to pull the changes to the inet4-porting branch. Any comments/improvements/feedback is appreciated.

Update (27.08.2020): Pull request was updated and now includes adaptations by @aarizaq for using inet::Packet throughout the stack and the latest bugfix for D2D on the master by @giovanninardini

### CODE REVIEW

**Comment by wischhof** [comment]
@torokati44 @rhornig We have updated the sources and fingerprint test to be compatible with inet 4.2.0 - could you provide a container with inet 4.2.0 (i.e. omnetpp/inet:o5.5.1-4.2.0) so that the checks can run with inet 4.2.0?

**Comment by torokati44** [comment]
I've started the build of the `o5.5.1-4.2.0` image, should be ready in about an hour.
Sorry you have to ask us every time... :D

**Comment by torokati44** [comment]
And it's done! Two images including the just released OMNeT++ 5.6 are also coming right up.

**Comment by wischhof** [comment]
> 
> 
> The OMNeT++ version is just 5.6, not 5.6.0 - slightly inconsistent, I know, but that's how the git tags and the announcements and all that mention it...

Thanks a lot for the quick info! Now the checks pass.

**Comment by wischhof** [comment]
Sorry, clicked to fast - accidently closed this pull request instead of the other one (related to master). Reopened now.

**Pull request merged**
